services:
  - type: web
    name: pointhit-backend
    env: node
    buildCommand: npm install
    startCommand: npm run start:backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000